#!/bin/bash
#wrapper for CLI shell and DIAG test
EXE_FILE="$(realpath $0)"
DIR="$(dirname $EXE_FILE)"
cd $DIR

#check necessary tools
#sudo apt-get -y install i2c-tools
#ACPI:
#  acpidump, iasl
#SMBIOS table:
#  dmidecode
#
#python-serial (用於 UART)
#nvme-cli (用於 NVMe)
#smartmontools (用於 SMART)
#ipmitool (用於 IPMI)
#lm-sensors (用於 CPU 溫度)
#usbutils (用於 USB)
#i2c/smbus
#sudo apt-get install build-essential

if [[ $1 == help ]] || [[ -z $1 ]]; then
    echo "Usage:"
    echo "$0 --help"
    echo "$0 list"
    echo "$0 categories"
    echo "$0 run cpu"
    echo "$0 run cpu/test_cpu_core.py"
    echo
    echo "Folder:"
    echo "  config folder for testcase setting"
    echo "  logs folder for testcase debug logs and test summary"
    echo
    echo "Testcase:   $(find testcase -type d -name "[a-zA-Z]*" | sed -e 's/^testcase[\/]*//g'| xargs)"
    echo
    echo "Installed CLI command:"
	.venv/bin/python ./cli_shell.py -c info | sed 's/^/  /g'
	echo "Installed test cases:"
	.venv/bin/python ./diag_test.py list | sed 's/^/  /g'
fi

$DIR/.venv/bin/python ./cli_shell.py "$@"
exit 0

if [[ -z $1 ]]; then
    $DIR/.venv/bin/python ./cli_shell.py $@
    exit 
fi

$DIR/.venv/bin/python ./diag_test.py $@

[[ $1 == run ]] && echo "last log:" && ls -lrt logs | tail -n 2